package com.example.panindia.model.bookingDetail.bookingDetailResponce

data class Passenger(
    val AddressLine1: String,
    val City: String,
    val ContactNo: String,
    val CountryCode: String,
    val DateOfBirth: String,
    val DocumentDetails: Any,
    val Email: String,
    val FFAirlineCode: String,
    val FFNumber: String,
    val Fare: FareX,
    val FirstName: String,
    val GSTCompanyAddress: String,
    val GSTCompanyContactNumber: String,
    val GSTCompanyEmail: String,
    val GSTCompanyName: String,
    val GSTNumber: String,
    val Gender: Int,
    val IsLeadPax: Boolean,
    val IsPANRequired: Boolean,
    val IsPassportRequired: Boolean,
    val LastName: String,
    val Nationality: String,
    val PAN: String,
    val PassportNo: String,
    val PaxId: Int,
    val PaxType: Int,
    val SegmentAdditionalInfo: List<SegmentAdditionalInfo>,
    val Ssr: List<Ssr>,
    val Ticket: Ticket,
    val Title: String
)